name: "Build and push to Docker Hub"

on:
  push:
    branches: [ "version-4" ]

jobs:
  docker:
    environment: Production
    runs-on: ubuntu-latest
    steps:
      - name: Install git
        run: sudo apt-get install git --yes
      - name: Validate git
        run: git rev-parse HEAD
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Docker Hub Login
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pinhead-website:${{ github.sha }}, ${{ secrets.DOCKERHUB_USERNAME }}/pinhead-website:preview, ${{ secrets.DOCKERHUB_USERNAME }}/pinhead-website:version-4